/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiazhiri_practice_util_NDKUtil */

#ifndef _Included_com_xiazhiri_practice_util_NDKUtil
#define _Included_com_xiazhiri_practice_util_NDKUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiazhiri_practice_util_NDKUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiazhiri_practice_util_NDKUtil_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
